# === experiment metadata === #
subject: sbj02
fs: 1000
train:
  labels:
    - ses_1.mat
    - ses_2.mat
    - ses_3.mat
    - ses_4.mat
  mat:
    - data_block001.mat
    - data_block002.mat
    - data_block003.mat
    - data_block004.mat
  trigger:
    - ses01.mat
    - ses02.mat
    - ses03.mat
    - ses04.mat
  rest:
    - data_rest001.mat
    - data_rest001.mat
    - data_rest001.mat
    - data_rest001.mat
val:
  labels:
    - val_1.mat
    - val_2.mat
    - val_3.mat
    - val_4.mat
    - val_5.mat
    - val_6.mat
  mat:
    - data_val001.mat
    - data_val002.mat
    - data_val003.mat
    - data_val004.mat
    - data_val005.mat
    - data_val006.mat

  trigger:
    - val01.mat
    - val02.mat
    - val03.mat
    - val04.mat
    - val05.mat
    - val06.mat

  rest:
    - data_rest001.mat
    - data_rest001.mat
    - data_rest001.mat
    - data_rest002.mat
    - data_rest002.mat
    - data_rest002.mat