# ==== Dataset ==== #
dataset: Brennan2018
seqLengthInSeconds: 3

# ==== Training ==== #
batch_size: 64
lr: 0.001
epochs: 500
last4layers: True # if True, the brain_encoder's emsize will be 1024, not 512
before: False      # (if last4layers: either before drop, residuals, and layer_norm or after)

# ==== Architecture ==== #
D1: 270
D2: 320
F: 512
K: 32
p_spatial_drop: 0.1
d_drop: 0.01

wav2vec_model: xlsr_53_56k