# ==== Dataset ==== #
dataset: Brennan2018

# ==== Training ==== #
# 🔥 FIXME: with too large a batchsize there isn't enough 
# 🔥 FIXME: samples in the eval set, and the CLIPLoss produces nans silently
batch_size: 64 

lr: 0.001
lr_scheduler: multistep
lr_exp_gamma: 0.99
lr_step_numsteps: 5
lr_multistep_mlstns: [0.4, 0.6, 0.8, 0.9]
lr_step_gamma: 0.5
epochs: 500
reduction: "mean"
clamp: False
clamp_lim: 20

# ==== Architecture ==== #
D1: 270
D2: 320
F: 512 # NOTE: because if you set last4layers=False, then it's set to 1024 in the dataset class
K: 32
d_drop: 0.3
# When calculating softmax for spatial attention in each iteration, we drop
# channels that are within the distance d_drop from a randomly selected channel

wav2vec_model: xlsr_53_56k

# == Hyperparameters that datasets should share === #
preprocs:
  audio_resample_rate: 16000 # before wav2vec
  lowpass_filter_width: 128

  brain_resample_rate: 120 # Hz
  brain_filter_low: 1.0 # Hz
  brain_filter_high: 60 # Hz

  seq_len_sec: 3        # segment length in seconds
  baseline_len_sec: 0.5 # baseline period in seconds
  shift_brain: True
  shift_len: 150 # ms

  last4layers: True # if True, the brain_encoder's emsize will be 1024, not 512
  before: False # (if last4layers: either before drop, residuals, and layer_norm or after)
