# ==== Dataset ==== #
dataset: Gwilliams2022
num_subjects: 27

# ==== Training ==== #
batch_size: 64
lr: 0.001
epochs: 50

# ==== Architecture ==== #
D1: 270
D2: 320
F: 1024
K: 32

wav2vec_model: xlsr_53_56k

# == Hyperparameters that datasets should share === #
preprocs:
  audio_resample_rate: 16000 # before wav2vec
  lowpass_filter_width: 128

  brain_resample_rate: 120 # Hz
  brain_filter_low: 1.0 # Hz
  brain_filter_high: 60 # Hz

  seq_len: 3 # segment length in seconds

  shift_brain: True
  shift_len: 150 # ms

  last4layers: True
  before: True